/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./src/modules/PulsesViewer2/components/Chart.vue')['default']
    Config: typeof import('./src/modules/PulsesViewer/stores/config.js')['default']
    Esp32: typeof import('./src/modules/PulsesViewer/composables/esp32.js')['default']
    ESP32RMT: typeof import('./src/modules/PulsesViewer/stores/ESP32RMT.js')['default']
    'HelloWorld.spec': typeof import('./src/components/__tests__/HelloWorld.spec.js')['default']
    'ICi:addRow': typeof import('~icons/ci/add-row')['default']
    'IFa:close': typeof import('~icons/fa/close')['default']
    'IFluent:listBarTreeOffset16Filled': typeof import('~icons/fluent/list-bar-tree-offset16-filled')['default']
    'IFluentEmojiHighContrast:orangeSquare': typeof import('~icons/fluent-emoji-high-contrast/orange-square')['default']
    'ILucide:locateFixed': typeof import('~icons/lucide/locate-fixed')['default']
    'IMaterialSymbols:helpOutline': typeof import('~icons/material-symbols/help-outline')['default']
    'IMaterialSymbols:settingsOutline': typeof import('~icons/material-symbols/settings-outline')['default']
    'IMaterialSymbols:zoomInMapRounded': typeof import('~icons/material-symbols/zoom-in-map-rounded')['default']
    'IMdi:edit': typeof import('~icons/mdi/edit')['default']
    'IMdi:editOutline': typeof import('~icons/mdi/edit-outline')['default']
    'IMingcute:leftFill': typeof import('~icons/mingcute/left-fill')['default']
    'IMingcute:rightFill': typeof import('~icons/mingcute/right-fill')['default']
    'IOoui:move': typeof import('~icons/ooui/move')['default']
    'ITabler:trash': typeof import('~icons/tabler/trash')['default']
    'ITwemoji:raccoon': typeof import('~icons/twemoji/raccoon')['default']
    'IUil:plus': typeof import('~icons/uil/plus')['default']
    MeasurementsMeta: typeof import('./src/modules/PulsesViewer/components/MeasurementsMeta.vue')['default']
    Panzoom: typeof import('./src/modules/PulsesViewer/stores/panzoom.js')['default']
    Pulses: typeof import('./src/modules/PulsesViewer/stores/pulses.js')['default']
    PulsesViewer: typeof import('./src/modules/PulsesViewer/PulsesViewer.vue')['default']
    PulsesViewerChart: typeof import('./src/modules/PulsesViewer/components/PulsesViewerChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stores: typeof import('./src/modules/PulsesViewer/stores/index.js')['default']
    UseESP32RMTMessages: typeof import('./src/modules/PulsesViewer/stores/useESP32RMTMessages.js')['default']
    UseESP32WebSocket: typeof import('./src/modules/PulsesViewer/composables/useESP32WebSocket.js')['default']
    UseGestures: typeof import('./src/modules/PulsesViewer/composables/useGestures.js')['default']
    UseMeasurements: typeof import('./src/modules/PulsesViewer/composables/useMeasurements.js')['default']
    View: typeof import('./src/modules/PulsesViewer/stores/view.js')['default']
  }
}
