/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelpPopover: typeof import('./src/components/HelpPopover.vue')['default']
    'ICarbon:moon': typeof import('~icons/carbon/moon')['default']
    'ICarbon:rowDelete': typeof import('~icons/carbon/row-delete')['default']
    'ICarbon:sun': typeof import('~icons/carbon/sun')['default']
    'IClarity:pinnedSolid': typeof import('~icons/clarity/pinned-solid')['default']
    'ILucide:locateFixed': typeof import('~icons/lucide/locate-fixed')['default']
    'IMdi:selectionRemove': typeof import('~icons/mdi/selection-remove')['default']
    'IMingcute:fullscreenExitFill': typeof import('~icons/mingcute/fullscreen-exit-fill')['default']
    'IMingcute:fullscreenFill': typeof import('~icons/mingcute/fullscreen-fill')['default']
    'IMingcute:leftFill': typeof import('~icons/mingcute/left-fill')['default']
    'IMingcute:rightFill': typeof import('~icons/mingcute/right-fill')['default']
    'IPh:alignLeftFill': typeof import('~icons/ph/align-left-fill')['default']
    'IPh:alignLeftSimpleFill': typeof import('~icons/ph/align-left-simple-fill')['default']
    'IPh:ambulanceLight': typeof import('~icons/ph/ambulance-light')['default']
    'IPh:bracketsSquareDuotone': typeof import('~icons/ph/brackets-square-duotone')['default']
    'IPh:check': typeof import('~icons/ph/check')['default']
    'IPh:checkCircleBold': typeof import('~icons/ph/check-circle-bold')['default']
    'IPh:clipboardText': typeof import('~icons/ph/clipboard-text')['default']
    'IPh:copy': typeof import('~icons/ph/copy')['default']
    'IPh:dotsSixVerticalBold': typeof import('~icons/ph/dots-six-vertical-bold')['default']
    'IPh:dotsThreeOutlineFill': typeof import('~icons/ph/dots-three-outline-fill')['default']
    'IPh:filePlusBold': typeof import('~icons/ph/file-plus-bold')['default']
    'IPh:gear': typeof import('~icons/ph/gear')['default']
    'IPh:githubLogoFill': typeof import('~icons/ph/github-logo-fill')['default']
    'IPh:pencilSimple': typeof import('~icons/ph/pencil-simple')['default']
    'IPh:plus': typeof import('~icons/ph/plus')['default']
    'IPh:question': typeof import('~icons/ph/question')['default']
    'IPh:scissors': typeof import('~icons/ph/scissors')['default']
    'IPh:trash': typeof import('~icons/ph/trash')['default']
    'IPh:x': typeof import('~icons/ph/x')['default']
    'IPh:xBold': typeof import('~icons/ph/x-bold')['default']
    'IRadixIcons:check': typeof import('~icons/radix-icons/check')['default']
    'IRadixIcons:chevronDown': typeof import('~icons/radix-icons/chevron-down')['default']
    'IRadixIcons:chevronUp': typeof import('~icons/radix-icons/chevron-up')['default']
    'ITabler:trash': typeof import('~icons/tabler/trash')['default']
    'ITwemoji:raccoon': typeof import('~icons/twemoji/raccoon')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PulsesViewEditPulsesDialog: typeof import('./src/modules/PulsesViewer/components/PulsesViewEditPulsesDialog.vue')['default']
    PulsesViewer: typeof import('./src/modules/PulsesViewer/index.vue')['default']
    PulsesViewItem: typeof import('./src/modules/PulsesViewer/components/PulsesViewItem.vue')['default']
    PulsesViewMeasurementMenu: typeof import('./src/modules/PulsesViewer/components/PulsesViewMeasurementMenu.vue')['default']
    PulsesViewMeasurementsDecoders: typeof import('./src/modules/PulsesViewer/components/PulsesViewMeasurementsDecoders.vue')['default']
    PulsesViewMeasurementsMeta: typeof import('./src/modules/PulsesViewer/components/PulsesViewMeasurementsMeta.vue')['default']
    PulsesViewMeasurementsMetaCard: typeof import('./src/modules/PulsesViewer/components/PulsesViewMeasurementsMetaCard.vue')['default']
    PulsesViewMeasurementsRects: typeof import('./src/modules/PulsesViewer/components/PulsesViewMeasurementsRects.vue')['default']
    PulsesViewPulsesStoreNavbar: typeof import('./src/modules/PulsesViewer/components/PulsesViewPulsesStoreNavbar.vue')['default']
    PulsesViewRoot: typeof import('./src/modules/PulsesViewer/components/PulsesViewRoot.vue')['default']
    PulsesViewSessionSelecotr: typeof import('./src/modules/PulsesViewer/components/PulsesViewSessionSelecotr.vue')['default']
    PulsesViewTicks: typeof import('./src/modules/PulsesViewer/components/PulsesViewTicks.vue')['default']
    PulsesViewWidthMeasure: typeof import('./src/modules/PulsesViewer/components/PulsesViewWidthMeasure.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPopover: typeof import('./src/components/SettingsPopover.vue')['default']
    ToastContainer: typeof import('./src/components/ToastContainer.vue')['default']
  }
}
